### ISSUE TITLE
HotChocolate.Types.Relay.UsePaging does not limit queries

### ISSUE THREAD

**Issue by TylerBrinks** [ChilliCream/hotchocolate-examples#25]
Using the Conference Planner project as a reference, decorating queries with the `[HotChocolate.Types.Relay.UsePaging] `returns all results by default.  The original `[HotChocolate.Types.UsePagingAttribute]` had a default paging and maximum page size.

Is there a way with the Relay paging attribute to limit an IQueryable to result to prevent querying an entire table?  

For example, the following track queries are both valid

`{
  tracks(first: 5){
    nodes{
      name
    }
  }
}`

`{
  tracks{
    nodes{
      name
    }
  }
}`

The former returns 5 results while the later returns every result in the table.  This is problematic for large data sets.

**Comment by michaelstaib** [comment]
Yes, there is with version 11 we have made this super easy. 

Set it globally:

```csharp
service
    .AddGraphQL()
    ....
    .SetPagingOptions(new PagingOptions { DefaultPageSize = 5  })
    ....
```

or locally on the attribute:

```csharp
[UsePaging(DefaultPageSize = 5)]
```
