### ISSUE TITLE
An item with the same key has already been added. Key: Query

### ISSUE THREAD

**Issue by tuan2174** [ChilliCream/hotchocolate-examples#30]
When running all the projects, the gateway project is unable to fetch remote schemas on Banana UI.

**Comment by mennis-lseg** [comment]
We are seeing the same issue.

**Comment by mennis-lseg** [comment]
I removed the second `extend type Query` from the Stitching.graphql file and the error went away. However, I am only seeing the remaining Query from that file and I do not see any of the queries from the other services.
